const defaultSetting: LX.AppSetting = {
  version: '2.0',
  'common.isAutoTheme': false,
  'common.langId': null,
  'common.apiSource': '',
  'common.sourceNameType': 'alias',
  'common.shareType': 'system',
  'common.isAgreePact': false,
  'common.isShowWelcome': false,
  'common.autoHidePlayBar': true,
  'common.drawerLayoutPosition': 'left',
  'common.homePageScroll': true,
  'common.allowProgressBarSeek': true,
  'common.showBackBtn': false,
  'common.showExitBtn': true,
  'common.useSystemFileSelector': true,
  'common.alwaysKeepStatusbarHeight': false,

  'common.isShowAnimation': true,
  'common.randomAnimate': true,

  'player.startupAutoPlay': false,
  'player.startupPushPlayDetailScreen': false,
  'player.togglePlayMethod': 'listLoop',
  'player.playQuality': '128k',
  'player.isSavePlayTime': false,
  'player.volume': 1,
  'player.isMute': false,
  'player.playbackRate': 1,
  'player.cacheSize': '1024',
  'player.timeoutExit': '',
  'player.timeoutExitPlayed': true,
  'player.isAutoCleanPlayedList': false,
  'player.isHandleAudioFocus': true,
  'player.autoSkipOnError': false,
  'player.isPlayLxlrc': false,
  'player.isSwapLyricTranslationAndRoma': false,
  'player.isEnableAudioOffload': true,
  'player.isShowLyricTranslation': false,
  'player.isShowLyricRoma': false,
  'player.isShowNotificationImage': true,
  'player.isS2t': false,
  'player.isShowBluetoothLyric': false,
  'player.isShowBluetoothFullLyric': false,

  // 'playDetail.isZoomActiveLrc': false,
  // 'playDetail.isShowLyricProgressSetting': false,
  'playDetail.style.align': 'left',
  'playDetail.vertical.style.lrcFontSize': 210,
  'playDetail.horizontal.style.lrcFontSize': 220,
  'playDetail.isShowLyricProgressSetting': false,
  'playDetail.isZoomActiveLrc': false,
  'playDetail.lyricDelayScroll': 600,
  'playDetail.progressStyle': 'full',

  'desktopLyric.enable': false,
  'desktopLyric.isLock': false,
  'desktopLyric.width': 100,
  'desktopLyric.maxLineNum': 5,
  'desktopLyric.isSingleLine': false,
  'desktopLyric.showToggleAnima': true,
  'desktopLyric.position.x': 0,
  'desktopLyric.position.y': 0,
  'desktopLyric.textPosition.x': 'left',
  'desktopLyric.textPosition.y': 'top',
  'desktopLyric.style.fontSize': 180,
  'desktopLyric.style.opacity': 100,
  'desktopLyric.style.lyricUnplayColor': 'rgba(255, 255, 255, 1)',
  'desktopLyric.style.lyricPlayedColor': 'rgba(7, 197, 86, 1)',
  'desktopLyric.style.lyricShadowColor': 'rgba(0, 0, 0, 0.6)',
  'desktopLyric.lineGap': 0,
  'desktopLyric.isZoomActiveLine': false,
  'desktopLyric.style.lyricPlayedColorEnd': 'rgba(7, 197, 86, 1)',
  'desktopLyric.style.fontWeight': 400,
  'desktopLyric.fontFamily': '',
  'desktopLyric.direction': 'horizontal',
  'desktopLyric.scrollAlign': 'center',
  'desktopLyric.textAlign': 'center',
  'desktopLyric.ellipsisMode': false,
  'desktopLyric.autoHideOnPause': false,

  'search.isShowHotSearch': false,
  'search.isShowHistorySearch': false,
  'search.isAutoClear': false,
  'odc.isAutoClearSearchInput': false,
  'odc.isAutoClearSearchList': false,

  'search.isFocusSearchBox': false,

  'list.isClickPlayList': false,
  'list.isShowSource': true,
  'list.isShowAlbumName': false,
  'list.isShowInterval': true,
  'list.isSaveScrollLocation': true,
  'list.addMusicLocationType': 'top',
  'list.actionButtonsVisible': false,

  'download.fileName': '歌名 - 歌手',
  'download.maxDownloadNum': '3',
  'download.skipExistFile': true,
  'download.isDownloadLrc': false,
  'download.isUseOtherSource': false,
  'download.quality': '128k',
  'download.savePath': '',
  'download.groupByList': false,
  'download.embedCover': false,
  'download.embedLyric': false,
  'download.embedLyricTranslation': false,
  'download.embedLyricRoma': false,
  'download.embedLyricLxlrc': false,
  'download.lyricEncoding': 'utf-8',
  'download.completeNotification': true,

  'sync.enable': false,
  'sync.mode': 'client',
  'sync.server.port': '23332',
  'sync.client.host': '',
  'sync.server.maxSsnapshotNum': '10',

  'network.proxy.enable': false,
  'network.proxy.host': '',
  'network.proxy.port': '',

  'version.githubMirror': '',

  'openAPI.enable': false,
  'openAPI.port': '23330',
  'openAPI.bindLan': false,

  // 'theme.id': 'blue_plus',
  'theme.id': 'green',
  'theme.lightId': 'green',
  'theme.darkId': 'black',
  'theme.hideBgDark': false,
  'theme.dynamicBg': false,
  'theme.fontShadow': false,
}


// 使用新年皮肤
if (new Date().getMonth() < 2) {
  defaultSetting['theme.id'] = 'happy_new_year'
  defaultSetting['desktopLyric.style.lyricPlayedColor'] = 'rgba(255, 18, 34, 1)'
}

export default defaultSetting
